#!/usr/bin/env bash
# This script stops the 4-to_infinity_and_beyond process

# Find the PID of the process using pgrep
pid=$(pgrep -f "To infinity and beyond")

# Check if the PID is not empty
if [ -n "$pid" ]; then
    # Send the SIGINT signal to the process
    kill -2 "$pid"
    echo "Process stopped successfully"
else
    echo "Process not found"
fi
