#!/usr/bin/env bash
# This script generates a story based on the content of the /etc/passwd file

# Read /etc/passwd line by line using a while loop
while IFS=: read -r username _ uid gid info home shell; do
    # Extract the group name based on the group id
    group=$(getent group "$gid" | cut -d: -f1)
    # Extract the command or shell used by the user
    command_shell=$(basename "$shell")
    # Extract the user ID info
    id_info=$(finger "$username" | awk -F': ' '/Name:/{print $2}')

    # Print the story
    echo "The user $username is part of the $group gang, lives in $home and rides $command_shell."
    echo "User ID's place is protected by the passcode $info, more info about the user here: $id_info"
    echo
done < /etc/passwd
