#!/usr/bin/env bash
# This script displays numbers from 1 to 20 with special messages for certain iterations

# Initialize counter
counter=1

# Loop from 1 to 20
while [ $counter -le 20 ]; do
    # Check for special cases
    case $counter in
        4)
            echo "$counter"
            echo "bad luck from China"
            ;;
        9)
            echo "$counter"
            echo "bad luck from Japan"
            ;;
        17)
            echo "$counter"
            echo "bad luck from Italy"
            ;;
        *)
            echo "$counter"
            ;;
    esac
    ((counter++))
done
